version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/var/www/html/logs
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=judge_system
      - MYSQL_USER=judge_user
      - MYSQL_PASSWORD=secure_password
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=secure_root_password
      - MYSQL_DATABASE=judge_system
      - MYSQL_USER=judge_user
      - MYSQL_PASSWORD=secure_password
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql_data: