version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/www/html/logs
      - ./ssl:/var/www/html/ssl
    environment:
      - MYSQL_HOST=judge-mysql-judge-mysql.l.aivencloud.com
      - MYSQL_DATABASE=defaultdb
      - MYSQL_USER=avnadmin
      - MYSQL_PASSWORD=AVNS_Y4Hy2MeZg6KSrviWwhI
      - MYSQL_PORT=21509
volumes:
  mysql_data: